apiVersion: apps/v1
kind: Deployment
metadata:
  name: prmd77-deploy
  labels:
    app: prmd77-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: prmd77-app
  template:
    metadata:
      labels:
        app: prmd77-app
    spec:
      containers:
      - name: prmd77-container
        image: prmd77/sa-mywebapp:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: prmd77-np-service
  labels:
    app: prmd77-np-app
spec:
  selector:
    app: prmd77-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 31028
