apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app-deployment
  labels:
    app: pramod-deploy-lbl
spec:
  replicas: 3
  selector:
    matchLabels:
      app: pramod-app
  template:
    metadata:
      labels:
        app: pramod-app
    spec:
      containers:
      - name: pramod-container
        image: prmd77/my-app-image:latest
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: pramod-np-service
  labels:
    app: pramod-np-app
spec:
  selector:
    app: pramod-deploy-lbl

  type: NodePort
  ports:
  - nodePort: 30007
    port: 8080
    targetPort: 8080
